spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jpa
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 5
        default_batch_fetch_size: 500

logging:
  level:
    org:
      hibernate:
        type: trace
